-- Tabla de configuración para WhatsApp
CREATE TABLE IF NOT EXISTS public.configuracion (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  telefono text null,
  constraint configuracion_pkey primary key (id)
) TABLESPACE pg_default;

-- Insertar registro inicial si no existe
INSERT INTO public.configuracion (telefono) 
SELECT '5491112345678' 
WHERE NOT EXISTS (SELECT 1 FROM public.configuracion LIMIT 1);

-- Habilitar RLS
ALTER TABLE public.configuracion ENABLE ROW LEVEL SECURITY;

-- Política para permitir lectura y escritura a usuarios autenticados
CREATE POLICY "Permitir acceso completo a usuarios autenticados" ON public.configuracion
  FOR ALL USING (auth.role() = 'authenticated');
