-- Tabla de configuración web para banner y otros elementos de la home
CREATE TABLE IF NOT EXISTS public.configuracion_web (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  banner text null, -- URL de la imagen del banner
  constraint configuracion_web_pkey primary key (id)
) TABLESPACE pg_default;

-- Insertar registro inicial si no existe
INSERT INTO public.configuracion_web (banner) 
SELECT null 
WHERE NOT EXISTS (SELECT 1 FROM public.configuracion_web LIMIT 1);

-- Habilitar RLS
ALTER TABLE public.configuracion_web ENABLE ROW LEVEL SECURITY;

-- Política para permitir lectura y escritura a usuarios autenticados
CREATE POLICY "Permitir acceso completo a usuarios autenticados" ON public.configuracion_web
  FOR ALL USING (auth.role() = 'authenticated');

-- Trigger para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_configuracion_web_updated_at 
    BEFORE UPDATE ON public.configuracion_web 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();