-- Crear tabla para configuración de zonas
create table public.configuracion_zonas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fk_id_zona bigint not null,
  telefono text not null,
  constraint configuracion_zonas_pkey primary key (id),
  constraint configuracion_zonas_fk_id_zona_fkey foreign key (fk_id_zona) references public.zonas (id) on delete cascade
) TABLESPACE pg_default;

-- Crear índice para mejorar el rendimiento de las consultas
create index configuracion_zonas_fk_id_zona_idx on public.configuracion_zonas (fk_id_zona);

-- Habilitar RLS (Row Level Security)
alter table public.configuracion_zonas enable row level security;

-- Crear políticas de seguridad (ajustar según tus necesidades)
create policy "Permitir acceso completo a configuracion_zonas" on public.configuracion_zonas
  for all using (true);
