-- Crear tabla para productos destacados por zona
CREATE TABLE IF NOT EXISTS public.productos_destacados_zona (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  fk_id_producto BIGINT NOT NULL,
  fk_id_zona BIGINT NOT NULL,
  orden INT DEFAULT 0, -- Para ordenar los productos destacados
  activo BOOLEAN DEFAULT TRUE,
  CONSTRAINT productos_destacados_zona_pkey PRIMARY KEY (id),
  CONSTRAINT productos_destacados_zona_fk_producto FOREIGN KEY (fk_id_producto)
    REFERENCES public.productos (id) ON DELETE CASCADE,
  CONSTRAINT productos_destacados_zona_fk_zona FOREIGN KEY (fk_id_zona)
    REFERENCES public.zonas (id) ON DELETE CASCADE,
  -- Evitar duplicados: un producto solo puede estar destacado una vez por zona
  CONSTRAINT productos_destacados_zona_unique UNIQUE (fk_id_producto, fk_id_zona)
) TABLESPACE pg_default;

-- Crear índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS productos_destacados_zona_producto_idx
  ON public.productos_destacados_zona (fk_id_producto);
CREATE INDEX IF NOT EXISTS productos_destacados_zona_zona_idx
  ON public.productos_destacados_zona (fk_id_zona);
CREATE INDEX IF NOT EXISTS productos_destacados_zona_activo_idx
  ON public.productos_destacados_zona (activo);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.productos_destacados_zona ENABLE ROW LEVEL SECURITY;

-- Crear política de seguridad (ajustar según tus necesidades)
CREATE POLICY "Permitir acceso completo a productos_destacados_zona"
  ON public.productos_destacados_zona
  FOR ALL USING (true);

-- Comentarios para documentación
COMMENT ON TABLE public.productos_destacados_zona IS 'Tabla para gestionar productos destacados por zona';
COMMENT ON COLUMN public.productos_destacados_zona.orden IS 'Orden de visualización del producto destacado (menor número = mayor prioridad)';
COMMENT ON COLUMN public.productos_destacados_zona.activo IS 'Indica si el producto destacado está activo para mostrar';
