-- Tabla para gestionar stock por sucursales
CREATE TABLE IF NOT EXISTS public.stock_sucursales (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  fk_id_producto bigint not null,
  fk_id_zona bigint not null,
  stock integer not null default 0,
  stock_minimo integer null default 0,
  activo boolean not null default true,
  constraint stock_sucursales_pkey primary key (id),
  constraint stock_sucursales_producto_fkey foreign key (fk_id_producto) references productos (id) on delete cascade,
  constraint stock_sucursales_zona_fkey foreign key (fk_id_zona) references zonas (id) on delete cascade,
  constraint stock_sucursales_unique_producto_zona unique (fk_id_producto, fk_id_zona)
) TABLESPACE pg_default;

-- Habilitar RLS
ALTER TABLE public.stock_sucursales ENABLE ROW LEVEL SECURITY;

-- Política para permitir acceso completo a usuarios autenticados
CREATE POLICY "Permitir acceso completo a usuarios autenticados" ON public.stock_sucursales
  FOR ALL USING (auth.role() = 'authenticated');

-- Trigger para actualizar updated_at automáticamente
CREATE TRIGGER update_stock_sucursales_updated_at 
    BEFORE UPDATE ON public.stock_sucursales 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Índices para mejorar performance
CREATE INDEX IF NOT EXISTS idx_stock_sucursales_producto ON public.stock_sucursales (fk_id_producto);
CREATE INDEX IF NOT EXISTS idx_stock_sucursales_zona ON public.stock_sucursales (fk_id_zona);
CREATE INDEX IF NOT EXISTS idx_stock_sucursales_activo ON public.stock_sucursales (activo);

-- Comentarios para documentación
COMMENT ON TABLE public.stock_sucursales IS 'Tabla para gestionar el stock de productos por sucursal/zona';
COMMENT ON COLUMN public.stock_sucursales.fk_id_producto IS 'ID del producto';
COMMENT ON COLUMN public.stock_sucursales.fk_id_zona IS 'ID de la zona/sucursal';
COMMENT ON COLUMN public.stock_sucursales.stock IS 'Cantidad de stock actual';
COMMENT ON COLUMN public.stock_sucursales.stock_minimo IS 'Stock mínimo requerido';
COMMENT ON COLUMN public.stock_sucursales.activo IS 'Si el registro está activo';

-- Verificar la estructura creada
SELECT 
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns 
WHERE table_name = 'stock_sucursales' 
  AND table_schema = 'public'
ORDER BY ordinal_position;