-- Crear tabla intermedia para relación muchos a muchos entre planes y categorías
CREATE TABLE public.planes_categorias (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fk_id_plan bigint not null,
  fk_id_categoria bigint not null,
  constraint planes_categorias_pkey primary key (id),
  constraint planes_categorias_fk_id_plan_fkey foreign key (fk_id_plan) references public.planes_financiacion (id) on delete cascade,
  constraint planes_categorias_fk_id_categoria_fkey foreign key (fk_id_categoria) references public.categorias (id) on delete cascade,
  constraint planes_categorias_unique unique (fk_id_plan, fk_id_categoria)
);

-- Crear índices para mejorar el rendimiento
CREATE INDEX planes_categorias_fk_id_plan_idx ON public.planes_categorias (fk_id_plan);
CREATE INDEX planes_categorias_fk_id_categoria_idx ON public.planes_categorias (fk_id_categoria);

-- Habilitar RLS
ALTER TABLE public.planes_categorias enable row level security;

-- Crear políticas de seguridad
CREATE POLICY "Permitir acceso completo a planes_categorias" on public.planes_categorias
  for all using (true);

-- Agregar comentarios para documentación
COMMENT ON TABLE public.planes_categorias IS 'Tabla intermedia para relación muchos a muchos entre planes de financiación y categorías';
COMMENT ON COLUMN public.planes_categorias.fk_id_plan IS 'ID del plan de financiación';
COMMENT ON COLUMN public.planes_categorias.fk_id_categoria IS 'ID de la categoría';

