-- Crear tabla para asociaciones por defecto entre productos y planes
create table public.producto_planes_default (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fk_id_producto bigint not null,
  fk_id_plan bigint not null,
  constraint producto_planes_default_pkey primary key (id),
  constraint producto_planes_default_fk_id_producto_fkey foreign key (fk_id_producto) references public.productos (id) on delete cascade,
  constraint producto_planes_default_fk_id_plan_fkey foreign key (fk_id_plan) references public.planes_financiacion (id) on delete cascade,
  constraint producto_planes_default_unique unique (fk_id_producto, fk_id_plan)
) TABLESPACE pg_default;

-- Crear índices para mejorar el rendimiento
create index producto_planes_default_fk_id_producto_idx on public.producto_planes_default (fk_id_producto);
create index producto_planes_default_fk_id_plan_idx on public.producto_planes_default (fk_id_plan);

-- Habilitar RLS (Row Level Security)
alter table public.producto_planes_default enable row level security;

-- Crear políticas de seguridad
create policy "Permitir acceso completo a producto_planes_default" on public.producto_planes_default
  for all using (true);
